"""Add default values to cost and paid_amount attributes in Student model

Revision ID: 47610580b3ea
Revises: 
Create Date: 2024-07-17 14:20:40.834254

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47610580b3ea"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cost", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("paid_amount", sa.Integer(), nullable=False, server_default="0")
        )

    # Remove server default after setting initial default values
    op.alter_column("students", "cost", server_default=None)
    op.alter_column("students", "paid_amount", server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_column("paid_amount")
        batch_op.drop_column("cost")

    # ### end Alembic commands ###
