"""added group_cost attribute to Group model

Revision ID: ccc5b859cfd2
Revises: 47610580b3ea
Create Date: 2024-07-17 19:23:04.450333

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ccc5b859cfd2"
down_revision = "47610580b3ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("group_cost", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###
    op.alter_column("groups", "group_cost", server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("groups", schema=None) as batch_op:
        batch_op.drop_column("group_cost")

    # ### end Alembic commands ###
