"""Create student_group_association table and update models

Revision ID: d015835979be
Revises: e2b201f56bc9
Create Date: 2024-07-18 14:22:59.354387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd015835979be'
down_revision = 'e2b201f56bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('students_group_id_fkey', 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###
